# roles/ocp-kdump/files/crash_trigger.yml

- name: Wait for worker node SSH to be reachable
  wait_for:
    host: "{{ worker_node }}"
    port: 22
    state: started
    timeout: 300

- name: Trigger kernel crash on worker node
  shell: ssh -o StrictHostKeyChecking=no core@{{ worker_node }} "echo c | sudo tee /proc/sysrq-trigger"
  ignore_errors: true

- name: Pause for 15 minutes before next crash
  pause:
    seconds: 900
